[book]
authors = ["sunface", "Hantong Chen"]
language = "zh-CN"
multilingual = true
title = "Rusty Book (锈书)"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/han-rs/rusty.han.rs"
edit-url-template = "https://github.com/han-rs/rusty.han.rs/edit/main/{path}"
additional-js = ["./theme/giscus.js"]
smart-punctuation = true
mathjax-support = true
hash-files = true

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = true
runnable = true
